{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file_005.Test_Credence_005 object at 0x0000023FAD34B650>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file_005.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "624b42f7-6db0-47eb-903d-b898a55bac53-attachment.txt", "type": "text/plain"}], "start": 1690770345000, "stop": 1690770345000, "uuid": "9d7a87ce-793d-4694-b2cd-6698da5531b1", "historyId": "3373f973f87d181b033c1208fbde30ae", "testCaseId": "3373f973f87d181b033c1208fbde30ae", "fullName": "test_file_005.Test_Credence_005#test_mul_004", "labels": [{"name": "suite", "value": "test_file_005"}, {"name": "subSuite", "value": "Test_Credence_005"}, {"name": "host", "value": "DESKTOP-USE2H4O"}, {"name": "thread", "value": "6988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file_005"}]}